name: 'Testing node component with different node versions'

on:
  workflow_dispatch:
  workflow_call:

jobs:
  testing:
    permissions:
      pull-requests: write
    uses: beuluis/reusable-workflows/.github/workflows/node-qa-testing.yml@main
