name: 'Testing node component with different node versions'

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    uses: beuluis/reusable-workflows/.github/workflows/node-qa-testing.yml@main
    with:
      test_command: 'npm run test:cov'
