name: 'Publish pack with next dist-tag'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  testing:
    uses: ./.github/workflows/node-qa-testing.yml

  publish-npm:
    needs: testing
    uses: beuluis/reusable-workflows/.github/workflows/npm-publish.yml@main
    with:
      dist_tag: 'next'
    secrets: inherit
